server:
  port: 18081
spring:
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        tags:
        - xiamen
        health-check-path: /ipanel/health
        prefer-ip-address: true
  datasource:
    url: jdbc:mysql://localhost:3306/marketingcompaign?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      idle-timeout: 600000
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
  sleuth:
    web:
      skip-pattern: /ipanel.*|/webjars.*|/v2/api-docs|/swagger.*|/favicon.ico|/service/clean
    sampler:
      probability: 0.1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /ipanel
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    prometheus:
      enabled: true
logging:
  path: /Users/luzhihao/tmp/log
  level:
    root: info
info:
  project: xiamen
  application:
    name: marketing-compaign-services